### ISSUE TITLE
Homework 6 Fixes

### ISSUE THREAD

**Issue by rtrana** [mbujnows1586/vacation-Able1#1]
Marcel, in order to get credit back on your homework score, fixes need to be completed by Thursday, March 25th at 9:00 p.m. (as part of the Homework 8 deadline) and *should be pushed to GitHub*. Once you complete all the fixes listed below, close this issue. Closing this issue will notify me - no need to resubmit to D2L. Please note that these fixes are needed for your final project, but you can only earn credit back on the assignment score if the fixes are submitted by the date/time listed above.

**Part I**: 0.20/0.25
- [ ] Missing the jQuery, Popper, and Bootstrap JavaScript files in the base fragment page. These should go in a block element outside of the body tags at the end of the file (see the lecture).

**Part II**: 0.23/0.25
- [ ] The navigation bar is collapsible, but it does not take up the full width in mobile view and is difficult to see. 
- [ ] There is an X on the hamburger icon in mobile view.

**Part III**: 0.20/0.25
- [ ] The form has not been fully styled with Bootstrap. See here: https://getbootstrap.com/docs/4.0/components/forms/

**Part IV**: 0.18/0.25
- [ ] Missing the footer.
- [ ] Missing the image on the home page.

**Current Score:** 0.81/1.0

*Additional Notes*
- [ ] Remove the controller java file that is hanging out in your root directory.

**Comment by mbujnows1586** [comment]
bootstrap has been updated
